// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejlqmeujtmvvuyktwnfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqbHFtZXVqdG12dnV5a3R3bmZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NDczNTgsImV4cCI6MjA2NzQyMzM1OH0.Ela5Gb5sscrWAiNvJdX6yxGn_WdxJtvpfCAAP0qvEQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});