// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fowafvnemhwinjsshcvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvd2Fmdm5lbWh3aW5qc3NoY3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMjI1MTEsImV4cCI6MjA2NzU5ODUxMX0.lTteijcXFmXIAPAT8zibd90D7AInrRlUJv4gHFpkbvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});